apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: dev
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            app: cronjob
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: postgres:17.0
            command:
            - /bin/sh
            - -c
            - export TIMESTAMP=$(date +"%Y%m%d%H%M%S"); export PGPASSWORD=$POSTGRES_PASSWORD; pg_dump -h $POSTGRES_SERVER -U $POSTGRES_USER -f /backups/backup-$TIMESTAMP.sql
            volumeMounts:
              - name: postgres-backup
                mountPath: "/backups"
            envFrom:
              - secretRef:
                  name: backend-secrets
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: postgres-backup

---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: dev
spec:
  containers:
  - name: pvc-inspector
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: /backups
        name: postgres-backup
  volumes:
    - name: postgres-backup
      persistentVolumeClaim:
        claimName: postgres-backup