apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  namespace: dev
spec:
  storageClassName: "standart" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: postgres-backup
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 0.5Gi
