apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  namespace: dev
spec:
  storageClassName: "standard" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
