apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # nodeName: fast-node, basic-node
      containers:
      - name: frontend
        image: frontend:0.7.1
        ports:
        - containerPort: 80
          name: frontend
        resources:
          requests:
            cpu: "75m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 7
          periodSeconds: 10