apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeName: node-fast
      initContainers:
      - name: init-postgres-db
        image: cgr.dev/chainguard/wait-for-it
        args:
        - postgres-postgresql.postgres.svc.cluster.local:5432
        - "--timeout=20" # Optional timeout in seconds
      - name: init-db-migrations
        image: backend:0.7.1
        command: ["/bin/sh", "-c"]
        args:
          - "python app/backend_pre_start.py && alembic upgrade head && python app/initial_data.py"
        env:
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: PROJECT_NAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET_KEY
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FIRST_SUPERUSER_PASSWORD
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_SERVER
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_PASSWORD
      containers:
      - name: backend
        image: backend:0.7.1
        ports:
        - containerPort: 8000
          name: backend
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/v1/utils/health-check/
            port: 8000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/v1/utils/health-check/
            port: 8000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 10
      # imagePullSecrets:
      # - name: backend-secrets
        env:
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: PROJECT_NAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET_KEY
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FIRST_SUPERUSER_PASSWORD
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_SERVER
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_PASSWORD

