apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: backend
    protocol: TCP
    port: 8000
    targetPort: 8000
    